spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: study
    password: study1234

jwt:
  secret: weorsigndfglk3#$

portone:
  rest_api_key: REST-API-KEY
  rest_api_secret: REST-API-SECRET